#!/bin/sh -ex

fatal()
{
  echo "fatal: $1" 1>&2
  exit 1
}

if [ $# -ne 1 ]
then
  fatal "usage: file.hex"
fi

FILE="$1"
shift

exec avrdude \
  -p m328p \
  -c arduino \
  -P /dev/ttyUSB0 \
  -b 57600 \
  -D \
  -v \
  -U flash:w:"${FILE}":i

